# Generated by Django 4.2.7 on 2025-08-01 21:46

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBIUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('aadhaar_number', models.CharField(help_text='12-digit Aadhaar number', max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('is_authority', models.BooleanField(default=False, help_text='Is this user an SBI Authority?')),
                ('is_defaulter', models.BooleanField(default=True, help_text='Mark as defaulter for tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'SBI User',
                'verbose_name_plural': 'SBI Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EventWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20, unique=True)),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event Weight',
                'verbose_name_plural': 'Event Weights',
            },
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('total_events', models.IntegerField()),
                ('total_users', models.IntegerField()),
                ('analysis_results', models.JSONField(default=dict)),
                ('raw_data_file', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Processed Data',
                'verbose_name_plural': 'Processed Data',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'SBI Login'), ('upi', 'UPI Transaction'), ('app_open', 'App Open')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_accuracy', models.FloatField(default=0.0, help_text='GPS accuracy in meters')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Event',
                'verbose_name_plural': 'User Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
