# Generated by Django 4.2.7 on 2025-08-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbiuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
